### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by Pirmuhammad9** [gmazzo/gradle-buildconfig-plugin#137] opened 2024-02-08 12:35 UTC
Hi, i faced this "unable to find method ''java.io.File com.squareup.kotlinpoet.FileSpec.writeTo(java.io.File)''
'java.io.File com.squareup.kotlinpoet.FileSpec.writeTo(java.io.File)'" issues, 
Is there any solution

**Comment by gmazzo** [comment] 2024-02-08 12:44
Is possibly a duplicated of #125? This is usually caused by another plugin added in a high order classloader (root project or `buildSrc`) that has KotlinPoet dependency outdated

**Comment by Pirmuhammad9** [comment] 2024-02-08 13:12
do you know any plugins that may cause it

**Comment by gmazzo** [comment] 2024-02-08 14:55
Nope, but you should be able to figure out by inspecting the build dependencies with a Gradle scan

**Comment by gmazzo** [comment] 2024-02-08 14:56
I'm closing it because the same reason than #125. This is not actually an issue with this plugin, but a configuration clash with another one

**Closed** 2024-02-08 14:55 UTC

**Comment by gmazzo** [comment] 2024-02-09 11:16
> Is possibly a duplicated of https://github.com/gmazzo/gradle-buildconfig-plugin/issues/125?

By the way @Pirmuhammad9 , I meant #131, see if it's workaround works for you

```kotlin
buildscript {
  dependencies {
    // Yuck. Need to force kotlinpoet:1.16.0 as that is what buildconfig uses.
    // CMP 1.6.0-x uses kotlinpoet:1.14.x. Gradle seems to force 1.14.x which then breaks
    // buildconfig.
    classpath("com.squareup:kotlinpoet:1.16.0")
  }
}
```
