### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by dhakehurst** [gmazzo/gradle-buildconfig-plugin#178] opened 2024-09-16 10:04 UTC
Hi,
Is there a way to add annotations ?

UseCase:
use in kotlin multiplatform project with multiple modules.

I generate a BuildConfig for each module.

Kotlin (for some reason I don't understand and disagree with) generates javascript files that ignore all package names.
thus the typescript file that is generated contains multiple 'BuildConfig' classes.

I figure I can fix that by adding an '@JsName' annotation to the generated BuildConfig class that adds something unique.

(of course what I really want is that JS code generated by kotlin includes the namespaces, but that is an argument I am having with Kotlin)

**Comment by gmazzo** [comment] 2024-09-16 10:22
I never thought about this use case to be honest.

As a quick workaround, I'd suggest you change the default `BuildConfig` name for each class to something that is unique. 

As a second, you can use the `buildConfig.generator` API to set your own generator, the issue is that it would be pretty much useless as you'll need to fully implement it yourself. Currently both Kotlin and Java generators are final as they are (necessary) `data class`es.

I think I craft a quick PR to change this, so you'll able to customize the final output yourself.

**Comment by dhakehurst** [comment] 2024-09-16 14:31
It shouldn’t be needed.

But with kotlin removing package names.
I don’t see an alternative.

**Comment by gmazzo** [comment] 2024-09-17 13:06
Released as `v5.5.0`

**Comment by gmazzo** [comment] 2024-09-18 07:56
You can check an example of how to do it here:
```kotlin
buildConfig {
    generator = object : BuildConfigKotlinGenerator() {
        override fun adaptSpec(spec: TypeSpec) = spec.toBuilder()
            .addAnnotation(AnnotationSpec.builder(ClassName.bestGuess("kotlin.js.JsName"))
                .addMember("name = %S", spec.name!!)
                .build())
            .build()
    }
```
https://github.com/gmazzo/gradle-buildconfig-plugin/blob/main/demo-project/kts-multiplatform/build.gradle.kts#L25

As it's a very croncrete use case, I'm not going to documented on the readme. `generator`s are customizable and that's documented already.

**Closed by gmazzo** 2024-09-18 07:56 UTC

**Comment by dhakehurst** [comment] 2024-09-20 14:04
thanks
